env:
  global:
  - COMPONENT=front
  - TOOLS_DIR=$HOME/tools
  - PATH=$TOOLS_DIR/bin:$PATH
  - AWS_DEFAULT_REGION=eu-west-1
  - secure: ORz5ABmrQaOfamI0bFok6Mx8u5++pApK+VGZdlPnENNrQaGM9NIl9OAwscJZrqToDGB36A7LTS4W8xffP32WOJmuO9qGuAmEH41OG3EiiclcbgBHrMpH+U7A3Q+Z8+m1Igllz4qgOHU/P3oyjbh0ublgM+VL+Fxw67DMdJZaqQHurW0ph2fJzVmTZirYSPJ/MFIrkfshPhrjcjvzAOnrXTJUXVF/EnzAhTGOSsQQdfW0z4HCml7WaNS6B9wAAWtUC+Q1meynippl+emqzMuGSVPuvyZ9U0HVxiwZFuCBgrPf+3cehdufkgEB2DtOSxFk+qNscy9Tdzua+nDC4ukTqXSFFBcvOi2CGQ0dsPwy9Iq/EYq2OuvnIky9v0fYjwVnnJKqUEP2OClLOREQlZBp9wWiYLee+CNDxNVXG5vF2VovtMj6fsRDGpkdCDy+Wni0+IxnmhnNSQNyr84rqrx3nGrFMw0/agNO1Gwep2dS9Xtq7hAyLbQ4ULZ0YvH2UmAIXaI7sDKe5jc3pxUOuDQLGjs6LN5YhKSO/QLaJ1zX0jEM5Z8urV9cwLnG/6m24wYDs0apI7GLz/FMcb4PVkRJz7k+uCt2xlijlucs208v7nMtZsVfhhTT/ZT3bbHDsTbOUbaSuQl/AowWolvt09AsxoPytxEanIj6ei16PV+Fn6Y=
  - secure: iGqesjIFB7jc2duHD7v5dGyEI7iH6OJ2YV0B4dSdP2g0ulMUMD8xBRJt960lZv1Slfioe2A9F7m4ZWsy2XGFhpINZYf5w5pY2MOIJ/JwuglEn1WivrlHcTXgbS/VprCD8i4+XC72k9IHNaYIKlfY4VvF5NQ9fz2ePPid9hN+wdZRjorBn1EFuJi6v+dn/8LngrgDwl/zLaoAOcF7iQ+s4ZqLlJKbVCM763QA3oHdSinzjzsJGzixf9QHgKEtJEeNtLXKCqgWHMKs3fthha/YFITm1Dzlpc7IOXmdmp8Z3t4ymahA9oMrkDev+UlnpGZdH7zLipLiMJj4wQtnZYlI0w1bKQQgdDwRSONwt2MXjrY35XkKDRHUOIijSJfdJs871MNpZezcsu/ycAptTBJ0pUTVS1NO9nZ2Hw29P1GFJHo01ozFK2EJ+jCbecqkM0qp4/c5Z4V0djYb5kQNE3kNcdJpfbBWYxYZ11q/gtkahFMkfhtxXo3n2EJw8fGAenv6SM60UgH2WqFiZB20GoYfP+hfy+FMS1jwd0rOLaRZZRy8updqa3ukcIOtufEXebf5IuQ0DJ8muTGzPTBcPslGbN8M5oCVNW82GU3lCzJzFpuPKrAJLyDPiTen80OY+DOno1b5IhUbz7gNFMGUPRo8K+fBSNgp9z/MZi1myzjO2Ss=
language: bash
sudo: required
before_deploy:
- sudo pip install 'requests[security]' awscli
- "$TRAVIS_BUILD_DIR/tools/install_packages.sh $TOOLS_DIR"
deploy:
- provider: script
  skip_cleanup: true
  script: cd $TRAVIS_BUILD_DIR/tools && ./deploy.sh
