env:
  global:
  - COMPONENT=front
  - TOOLS_DIR=$HOME/tools
  - PATH=$TOOLS_DIR/bin:$PATH
  - AWS_DEFAULT_REGION=eu-west-1
  - secure:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqckxwTcdjKMuvJDBNvwmvCmj8GOe3ZJaAUYBIvBe53NgFfRC2ES8sMKyzY7J4M+5W34+cyytx6+NAhpgYKBAKvxAI43hjmAC3Lmsqgo8OSAbuSh6n+amzyq501PKs8wo1JH7HAYWnlXEpPfNgx6/cKG0rtuWEuzNlpPDKixoEvBXDkzIQuDiRPH33cQbKo4OqmuqxSuSVlwPJsc18HhigikmQzVoaZI0VeayeN07C8hefAxzVS0t5DOMTop1eZS3vC4iPW8U4xOEYY0D7Fg2IkHG4P1st4yd2BEk7eKhqL1NO79cF0yq3fevwJ0cm1NlfQ0jqTcEgDqsOCmaQDuFz linux@linux 
  
language: bash
sudo: required
before_deploy:
- sudo pip install 'requests[security]' awscli
- "$TRAVIS_BUILD_DIR/tools/install_packages.sh $TOOLS_DIR"
deploy:
- provider: script
  skip_cleanup: true
  script: cd $TRAVIS_BUILD_DIR/tools && ./deploy.sh
